const translations = {
  en: { tagline:"Interactive physics laboratories and inspectable hybrid-computing algorithms", language:"Language", eyebrow:"LOCAL · OPEN · EDUCATIONAL", title:"Explore matter, particles, and hybrid scientific computing.", intro:"This independent research-lab project brings together interactive QCD-matter models, neutrino communication, and inspectable hybrid-computing algorithms. Visualizations distinguish established physics from theoretical and hypothetical extensions.", matterTitle:"QCD Matter Lab", matterText:"Explore ordinary, dense, quark and strange matter, mesons, collider workspaces, gravitational-wave concepts, and author-labelled hypotheses.", openMatter:"Open matter laboratory →", commTitle:"Neutrino Communication Lab", commText:"Visualize a neutrino beam passing through rock to a detector, with an electromagnetic comparison channel.", openComm:"Open communication simulator →", hybridTitle:"Hybrid Algorithm Demonstrations", hybridText:"Start with an eight-qubit CUDA-Q Shor circuit, then switch to the ASIC–CUDA-Q pipeline or the complete multi-quark search without losing the selected language.", openHybrid:"Open the demonstrations →", multiTitle:"Multi-Quark Stable-System Search", multiText:"Trace constraints, DirectML GPU screening, deterministic ranking, RTL workload filtering, and reproducibility artifacts line by line.", openMulti:"Inspect the full algorithm →", chainTitle:"Matter Frontier Discovery Chain", chainText:"Coordinate non-overlapping multi-quark search cells across local CPU, DirectML GPU, FPGA and quantum adapters, with commitments and reproducible verification.", openChain:"Open architecture and testnet →", futureEyebrow:"PROJECT DIRECTION", futureText:"Future work: connect traceable lattice-QCD validation backends and cloud QPUs while preserving reproducible manifests, uncertainty records, and explicit scientific boundaries." },
  ru: { tagline:"Интерактивные физические лаборатории и прозрачные гибридные алгоритмы", language:"Язык", eyebrow:"ЛОКАЛЬНО · ОТКРЫТО · ОБУЧАЮЩЕЕ", title:"Исследуйте материю, частицы и гибридные научные вычисления.", intro:"Независимый исследовательский проект объединяет интерактивные модели КХД-материи, нейтринную коммуникацию и прозрачные гибридные алгоритмы. Визуализации отделяют установленную физику от теоретических и гипотетических расширений.", matterTitle:"Лаборатория КХД-материи", matterText:"Исследуйте обычную, плотную, кварковую и странную материю, мезоны, коллайдерные среды, концепции гравитационных волн и авторские гипотезы с явными метками.", openMatter:"Открыть лабораторию материи →", commTitle:"Лаборатория нейтринной коммуникации", commText:"Визуализируйте нейтринный пучок, проходящий через породу к детектору, и сравните его с электромагнитным каналом.", openComm:"Открыть симулятор коммуникации →", hybridTitle:"Демонстрации гибридных алгоритмов", hybridText:"Начните с восьмикубитной схемы Шора на CUDA-Q, затем переключайтесь на конвейер ASIC–CUDA-Q или полный поиск мультикварковых систем без сброса выбранного языка.", openHybrid:"Открыть демонстрации →", multiTitle:"Поиск устойчивых мультикварковых систем", multiText:"Построчно проследите ограничения, DirectML GPU-скрининг, детерминированное ранжирование, RTL-фильтр нагрузки и артефакты воспроизводимости.", openMulti:"Разобрать полный алгоритм →", chainTitle:"Matter Frontier Discovery Chain", chainText:"Координируйте непересекающиеся ячейки мультикваркового поиска между локальными CPU, DirectML GPU, FPGA и квантовыми адаптерами с commitments и воспроизводимой проверкой.", openChain:"Открыть архитектуру и testnet →", futureEyebrow:"НАПРАВЛЕНИЕ ПРОЕКТА", futureText:"Будущая работа: подключение прослеживаемых lattice-QCD-бэкендов и облачных QPU при сохранении воспроизводимых manifests, неопределённостей и явных научных границ." },
  he: { tagline:"מעבדות פיזיקה אינטראקטיביות ואלגוריתמים היברידיים ניתנים לבדיקה", language:"שפה", eyebrow:"מקומי · פתוח · חינוכי", title:"לחקור חומר, חלקיקים וחישוב מדעי היברידי.", intro:"פרויקט מחקר עצמאי זה מאחד מודלים אינטראקטיביים של חומר QCD, תקשורת ניטרינו ואלגוריתמים היברידיים ניתנים לבדיקה. ההדמיות מבדילות בין פיזיקה מבוססת לבין הרחבות תיאורטיות והיפותטיות.", matterTitle:"מעבדת חומר QCD", matterText:"לחקור חומר רגיל, צפוף, קווארקי ומוזר, מזונים, סביבות מאיץ, מושגי גלי כבידה והיפותזות מחבר מסומנות.", openMatter:"פתיחת מעבדת החומר ←", commTitle:"מעבדת תקשורת ניטרינו", commText:"להדגים אלומת ניטרינו העוברת דרך סלע לגלאי, לצד ערוץ השוואה אלקטרומגנטי.", openComm:"פתיחת סימולטור התקשורת ←", hybridTitle:"הדגמות אלגוריתמים היברידיים", hybridText:"התחילו במעגל שור בן שמונה קיוביטים ב-CUDA-Q, ואז עברו לצינור ASIC–CUDA-Q או לחיפוש הרב־קווארקי המלא בלי לאבד את השפה שנבחרה.", openHybrid:"פתיחת ההדגמות ←", multiTitle:"חיפוש מערכות מרובות־קווארקים יציבות", multiText:"מעקב שורה אחר שורה אחר אילוצים, סינון DirectML GPU, דירוג דטרמיניסטי, מסנן עומס RTL ו-artifacts לשחזור.", openMulti:"פירוט האלגוריתם המלא ←", chainTitle:"Matter Frontier Discovery Chain", chainText:"תיאום תאי חיפוש רב־קווארקיים שאינם חופפים בין CPU מקומי, DirectML GPU, FPGA ומתאמים קוונטיים, עם התחייבויות ואימות ניתן לשחזור.", openChain:"פתיחת הארכיטקטורה וה-testnet ←", futureEyebrow:"כיוון הפרויקט", futureText:"עבודה עתידית: חיבור backends של lattice-QCD עם עקיבות ו-QPU בענן תוך שמירת manifests ניתנים לשחזור, רישומי אי־ודאות וגבולות מדעיים מפורשים." }
};
function setLanguage(lang) {
  const t=translations[lang]||translations.en;
  document.documentElement.lang=lang;
  document.documentElement.dir=lang==='he'?'rtl':'ltr';
  document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t[el.dataset.i18n]);
  localStorage.setItem('qcd-neutrino-language',lang);
  localStorage.setItem('mfl-pages-language',lang);
  const current=new URL(location.href);current.searchParams.set('lang',lang);history.replaceState(null,'',current);
  document.querySelectorAll('a[data-base-href]').forEach(link=>link.href=`${link.dataset.baseHref}?lang=${encodeURIComponent(lang)}`);
}
const requested=new URLSearchParams(location.search).get('lang');
const initial=['en','ru','he'].includes(requested)?requested:(localStorage.getItem('qcd-neutrino-language')||localStorage.getItem('mfl-pages-language')||'en');
const select=document.querySelector('#languageSelect');select.value=initial;select.addEventListener('change',()=>setLanguage(select.value));setLanguage(select.value);
