window.INSPECTOR_CONFIG = {
  copy: {
    en:{documentTitle:"Hybrid ASIC + CUDA-Q Demo · Matter Frontier Lab",eyebrow:"OPEN SOURCE · EXECUTABLE ARCHITECTURE DEMO",title:"One small algorithm across ASIC logic, host orchestration, and a CUDA-Q kernel.",intro:"Four integer candidates enter a synthesizable SystemVerilog filter. The host preserves the accepted two-bit address and asks a CUDA-Q Grover kernel to recover |11⟩. This page opens the exact repository code, line by line, and labels what is executed, optional, or illustrative.",flowTitle:"Click the live pipeline to open its code",flowIntro:"The host-reference and quantum-runtime paths can be prepared independently. The dashed RTL lane implements and verifies the same integer filter contract; it is not silently executed by the Python demo.",architectureTitle:"A narrow hybrid pipeline with explicit boundaries",stagesTitle:"Inspect every executable stage",sourcesTitle:"Files used by this demonstration",boundaryTitle:"What this demo proves — and what it does not"},
    ru:{documentTitle:"Демонстрация ASIC + CUDA-Q · Matter Frontier Lab",eyebrow:"ОТКРЫТЫЙ КОД · ИСПОЛНЯЕМАЯ ДЕМОНСТРАЦИЯ АРХИТЕКТУРЫ",title:"Один небольшой алгоритм на стыке ASIC-логики, host-оркестрации и ядра CUDA‑Q.",intro:"Четыре целочисленных кандидата поступают в синтезируемый SystemVerilog-фильтр. Host сохраняет принятый двухбитный адрес, а ядро Grover в CUDA‑Q восстанавливает |11⟩. Здесь можно открыть точный код репозитория построчно и увидеть, что исполняется, что опционально, а что является иллюстрацией.",flowTitle:"Нажмите на узел схемы, чтобы открыть его код",flowIntro:"Host-эталон и квантовую runtime-ветвь можно подготавливать независимо. Пунктирная RTL-дорожка реализует и проверяет тот же целочисленный контракт, но Python-демонстрация не выдаёт её за автоматически исполненную.",architectureTitle:"Узкий гибридный конвейер с явными границами",stagesTitle:"Разберите каждый исполняемый этап",sourcesTitle:"Файлы демонстрационного алгоритма",boundaryTitle:"Что демонстрация подтверждает — и чего не подтверждает"},
    he:{documentTitle:"הדגמת ASIC + CUDA-Q · Matter Frontier Lab",eyebrow:"קוד פתוח · הדגמת ארכיטקטורה ניתנת להרצה",title:"אלגוריתם קטן אחד על פני לוגיקת ASIC, תזמור מארח וליבת CUDA‑Q.",intro:"ארבעה מועמדים שלמים נכנסים למסנן SystemVerilog הניתן לסינתזה. המארח שומר את הכתובת הדו־סיבית שהתקבלה, וליבת Grover ב‑CUDA‑Q משחזרת את |11⟩. כאן נפתח קוד המאגר המדויק שורה אחר שורה ומסומן מה רץ, מה אופציונלי ומה המחשה.",flowTitle:"לחצו על צומת בתרשים כדי לפתוח את הקוד שלו",flowIntro:"ניתן להכין את נתיב ייחוס המארח ואת נתיב זמן הריצה הקוונטי באופן עצמאי. נתיב ה-RTL המקווקו מממש ומאמת את אותו חוזה שלמים, אך הדגמת Python אינה מציגה אותו כאילו הורץ אוטומטית.",architectureTitle:"צינור היברידי צר עם גבולות מפורשים",stagesTitle:"בדיקת כל שלב ניתן להרצה",sourcesTitle:"הקבצים המשמשים את ההדגמה",boundaryTitle:"מה ההדגמה מוכיחה — ומה לא"}
  },
  flow:{
    columns:5,rows:3,
    lanes:[
      {row:1,kind:"parallel",title:{en:"Host reference lane",ru:"Host-эталон",he:"נתיב ייחוס מארח"}},
      {row:2,kind:"parallel",title:{en:"Quantum runtime lane",ru:"Квантовая runtime-ветвь",he:"נתיב זמן ריצה קוונטי"}},
      {row:3,kind:"reference",title:{en:"RTL implementation and verification",ru:"RTL-реализация и проверка",he:"מימוש ואימות RTL"}}
    ],
    nodes:[
      {id:"records",stage:0,column:1,row:2,caption:{en:"Shared integer payload",ru:"Общая целочисленная запись",he:"מטען שלמים משותף"}},
      {id:"reference",stage:1,column:2,row:1,kind:"parallel",caption:{en:"Executed by run_demo",ru:"Исполняется в run_demo",he:"רץ בתוך run_demo"}},
      {id:"kernel",stage:3,column:2,row:2,kind:"parallel",caption:{en:"Prepared independently",ru:"Готовится независимо",he:"מוכן באופן עצמאי"}},
      {id:"rtl",stage:2,column:2,row:3,kind:"reference",caption:{en:"Synthesizable equivalent",ru:"Синтезируемый эквивалент",he:"מקבילה ניתנת לסינתזה"}},
      {id:"runtime",stage:4,column:3,row:2,caption:{en:"Optional CUDA-Q target",ru:"Опциональный таргет CUDA‑Q",he:"יעד CUDA-Q אופציונלי"}},
      {id:"join",stage:5,column:5,row:2,caption:{en:"Address check → result",ru:"Проверка адреса → результат",he:"בדיקת כתובת ← תוצאה"}}
    ],
    edges:[
      {from:"records",to:"reference",label:{en:"candidate records",ru:"записи кандидатов",he:"רשומות מועמדים"}},
      {from:"records",to:"rtl",kind:"reference",label:{en:"same port contract",ru:"тот же портовый контракт",he:"אותו חוזה יציאות"}},
      {from:"kernel",to:"runtime",label:{en:"compiled circuit",ru:"скомпилированная схема",he:"מעגל מקומפל"}},
      {from:"reference",to:"join",label:{en:"accepted ID 3",ru:"принятый ID 3",he:"מזהה 3 שהתקבל"}},
      {from:"runtime",to:"join",label:{en:"measurement counts",ru:"результаты измерений",he:"ספירות מדידה"}},
      {from:"rtl",to:"join",kind:"reference",label:{en:"contract parity",ru:"проверка эквивалентности",he:"שקילות חוזה"}}
    ],
    note:{en:"Parallel lanes show independent preparation or hardware work. Solid arrows are dependencies in the current host run; dashed arrows are committed implementation/verification relationships.",ru:"Параллельные дорожки показывают независимо подготавливаемые или аппаратные работы. Сплошные стрелки — зависимости текущего host-запуска; пунктир — связи реализации и проверки.",he:"נתיבים מקבילים מציגים הכנה עצמאית או עבודת חומרה. חצים מלאים הם תלויות בהרצת המארח הנוכחית; חצים מקווקווים הם קשרי מימוש ואימות."}
  },
  status:[
    {title:{en:"SystemVerilog RTL: committed",ru:"SystemVerilog RTL: добавлен",he:"SystemVerilog RTL: במאגר"},text:{en:"Synthesizable ready/valid filter plus a cycle-level testbench.",ru:"Синтезируемый ready/valid-фильтр и тактовый testbench.",he:"מסנן ready/valid הניתן לסינתזה ו-testbench מחזורי."}},
    {title:{en:"CUDA-Q: optional runtime",ru:"CUDA-Q: опциональная среда",he:"CUDA-Q: סביבת ריצה אופציונלית"},text:{en:"The kernel targets qpp-cpu portably; official Windows use is through WSL2.",ru:"Ядро переносимо работает с qpp-cpu; официальный запуск в Windows — через WSL2.",he:"הליבה מכוונת באופן נייד ל-qpp-cpu; ב-Windows ההרצה הרשמית היא דרך WSL2."}},
    {title:{en:"AMD GPU: separate DirectML path",ru:"AMD GPU: отдельный путь DirectML",he:"AMD GPU: נתיב DirectML נפרד"},text:{en:"The local Radeon accelerates committed DirectML workloads, not CUDA-Q's NVIDIA backend.",ru:"Локальная Radeon ускоряет имеющиеся DirectML-задачи, но не NVIDIA-бэкенд CUDA-Q.",he:"כרטיס Radeon המקומי מאיץ עומסי DirectML קיימים, לא את backend ה-NVIDIA של CUDA-Q."}}
  ],
  architecture:[
    {title:{en:"Candidate stream",ru:"Поток кандидатов",he:"זרם מועמדים"},text:{en:"Four deterministic integer records make the data contract visible.",ru:"Четыре детерминированные целочисленные записи делают контракт данных явным.",he:"ארבע רשומות שלמות ודטרמיניסטיות חושפות את חוזה הנתונים."}},
    {title:{en:"ASIC filter",ru:"ASIC-фильтр",he:"מסנן ASIC"},text:{en:"Conservation, color triality, Pauli permission, and threshold margin are checked in RTL.",ru:"В RTL проверяются сохранение, цветовая триальность, разрешение Паули и пороговый запас.",he:"שימור, triality צבע, היתר פאולי ומרווח סף נבדקים ב-RTL."}},
    {title:{en:"Host contract",ru:"Host-контракт",he:"חוזה מארח"},text:{en:"Accepted candidate 3 is mapped transparently to the two-qubit address |11⟩.",ru:"Принятый кандидат 3 прозрачно сопоставляется двухкубитному адресу |11⟩.",he:"מועמד 3 שהתקבל ממופה בשקיפות לכתובת הדו־קיוביטית |11⟩."}},
    {title:{en:"CUDA-Q kernel",ru:"Ядро CUDA-Q",he:"ליבת CUDA-Q"},text:{en:"A two-qubit oracle and diffusion step amplify the marked address before sampling.",ru:"Двухкубитный оракул и диффузионный шаг усиливают отмеченный адрес до измерения.",he:"אורקל דו־קיוביטי וצעד דיפוזיה מגבירים את הכתובת המסומנת לפני דגימה."}}
  ],
  stages:[
    {kicker:{en:"DATA CONTRACT",ru:"КОНТРАКТ ДАННЫХ",he:"חוזה נתונים"},title:{en:"Define the four candidate records",ru:"Определение четырёх кандидатов",he:"הגדרת ארבע רשומות המועמדים"},summary:{en:"The same integer fields can cross Python, an RTL testbench, and a later hardware bus without hidden floating-point semantics.",ru:"Одинаковые целочисленные поля проходят через Python, RTL-testbench и будущую аппаратную шину без скрытой семантики floating point.",he:"אותם שדות שלמים עוברים בין Python, testbench של RTL ואפיק חומרה עתידי ללא סמנטיקת נקודה צפה נסתרת."},source:"../scientific_backend/hybrid_quantum_asic_demo.py",sourceLabel:{en:"Python source",ru:"Исходник Python",he:"קוד Python"},start:"@dataclass(frozen=True)",end:"def asic_reference_filter",substeps:[{title:{en:"Record schema",ru:"Схема записи",he:"סכמת רשומה"},start:"@dataclass(frozen=True)",end:"DEMO_CANDIDATES"},{title:{en:"Deterministic inputs",ru:"Детерминированные входы",he:"קלטים דטרמיניסטיים"},start:"DEMO_CANDIDATES",end:"def asic_reference_filter"}],notes:[{contains:"class Candidate",text:{en:"Creates the immutable payload mirrored by the RTL port list.",ru:"Создаёт неизменяемую нагрузку, повторённую в списке RTL-портов.",he:"יוצר payload בלתי־משתנה המקביל לרשימת יציאות ה-RTL."}},{contains:"Candidate(3",text:{en:"Candidate 3 intentionally satisfies every filter and maps to binary address 11.",ru:"Кандидат 3 намеренно проходит все фильтры и соответствует двоичному адресу 11.",he:"מועמד 3 עומד בכוונה בכל המסננים וממופה לכתובת הבינארית 11."}}]},
    {kicker:{en:"SOFTWARE REFERENCE",ru:"ПРОГРАММНЫЙ ЭТАЛОН",he:"ייחוס תוכנה"},title:{en:"Mirror the ASIC acceptance logic",ru:"Повторение логики приёмки ASIC",he:"שיקוף לוגיקת הקבלה של ASIC"},summary:{en:"A short Python reference makes the hardware truth table testable before synthesis.",ru:"Короткий Python-эталон позволяет проверять таблицу истинности аппаратуры до синтеза.",he:"ייחוס Python קצר מאפשר לבדוק את טבלת האמת של החומרה לפני סינתזה."},source:"../scientific_backend/hybrid_quantum_asic_demo.py",sourceLabel:{en:"Python source",ru:"Исходник Python",he:"קוד Python"},start:"def asic_reference_filter",end:"if cudaq is not None",substeps:[{title:{en:"Margin",ru:"Пороговый запас",he:"מרווח"},start:"accepted:",end:"constraints_ok"},{title:{en:"Constraints",ru:"Ограничения",he:"אילוצים"},start:"constraints_ok",end:"if constraints_ok"},{title:{en:"Emit",ru:"Выдача",he:"פלט"},start:"if constraints_ok",end:"return accepted"}],notes:[{contains:"margin =",text:{en:"Computes threshold minus candidate energy using the same sign convention as RTL.",ru:"Вычисляет порог минус энергию кандидата с тем же знаком, что и RTL.",he:"מחשב סף פחות אנרגיית מועמד באותה מוסכמת סימן כמו RTL."}},{contains:"margin > candidate.uncertainty_mev",text:{en:"Requires positive separation beyond one stated uncertainty unit.",ru:"Требует положительного отделения больше одной указанной единицы неопределённости.",he:"דורש הפרדה חיובית מעבר ליחידת אי־ודאות אחת."}}]},
    {kicker:{en:"SYNTHESIZABLE ASIC STAGE",ru:"СИНТЕЗИРУЕМЫЙ ASIC-ЭТАП",he:"שלב ASIC ניתן לסינתזה"},title:{en:"Stream candidates through SystemVerilog",ru:"Поток кандидатов через SystemVerilog",he:"הזרמת מועמדים דרך SystemVerilog"},summary:{en:"The ready/valid module performs only stable integer comparisons and subtraction; it deliberately does not attempt to solve QCD.",ru:"Ready/valid-модуль выполняет только стабильные целочисленные сравнения и вычитание; он намеренно не пытается решать КХД.",he:"מודול ready/valid מבצע רק השוואות וחיסור שלמים יציבים; הוא אינו מנסה לפתור QCD."},source:"../hardware/hybrid_quantum_asic/hybrid_candidate_filter.sv",sourceLabel:{en:"SystemVerilog RTL",ru:"SystemVerilog RTL",he:"SystemVerilog RTL"},start:"// Matter Frontier Lab",substeps:[{title:{en:"Ports",ru:"Порты",he:"יציאות"},start:"module hybrid_candidate_filter",end:"logic signed [EW-1:0] margin_next"},{title:{en:"Combinational filter",ru:"Комбинационный фильтр",he:"מסנן צירופי"},start:"always_comb",end:"always_ff"},{title:{en:"Registered output",ru:"Регистровый выход",he:"פלט רשום"},start:"always_ff",end:"endmodule"}],notes:[{contains:"in_ready      =",text:{en:"Implements back-pressure: a new word is accepted only when the output slot is free or consumed.",ru:"Реализует back-pressure: новое слово принимается, когда выход свободен или считан.",he:"מיישם back-pressure: מילה חדשה מתקבלת רק כשהפלט פנוי או נצרך."}},{contains:"accepted       <=",text:{en:"Registers the exact conjunction that qualifies a candidate for host transfer.",ru:"Регистрирует точную конъюнкцию допуска кандидата к передаче host.",he:"רושם את הצירוף המדויק המאשר מועמד להעברה למארח."}}]},
    {kicker:{en:"QUANTUM KERNEL",ru:"КВАНТОВОЕ ЯДРО",he:"ליבה קוונטית"},title:{en:"Compile the two-qubit Grover circuit",ru:"Компиляция двухкубитной схемы Grover",he:"קומפילציית מעגל Grover דו־קיוביטי"},summary:{en:"The CUDA-Q decorator turns an ordinary-looking Python function into a quantum kernel containing preparation, oracle, diffusion, and measurement.",ru:"Декоратор CUDA-Q превращает Python-функцию в квантовое ядро с подготовкой, оракулом, диффузией и измерением.",he:"ה-decorator של CUDA-Q הופך פונקציית Python לליבה קוונטית עם הכנה, אורקל, דיפוזיה ומדידה."},source:"../scientific_backend/hybrid_quantum_asic_demo.py",sourceLabel:{en:"CUDA-Q Python",ru:"CUDA-Q Python",he:"CUDA-Q Python"},start:"if cudaq is not None",end:"def run_quantum_kernel",substeps:[{title:{en:"Compile guard",ru:"Проверка среды",he:"בדיקת סביבה"},start:"if cudaq is not None",end:"@cudaq.kernel"},{title:{en:"Oracle",ru:"Оракул",he:"אורקל"},start:"qubits =",end:"        x(qubits)"},{title:{en:"Diffusion + measure",ru:"Диффузия и измерение",he:"דיפוזיה ומדידה"},start:"        x(qubits)",end:"else:"}],notes:[{contains:"@cudaq.kernel",text:{en:"Asks CUDA-Q to compile the following function as a quantum kernel.",ru:"Поручает CUDA-Q скомпилировать следующую функцию как квантовое ядро.",he:"מורה ל-CUDA-Q לקמפל את הפונקציה הבאה כליבה קוונטית."}},{contains:"z.ctrl",text:{en:"Applies a controlled phase flip: first as the |11⟩ oracle, then inside Grover diffusion.",ru:"Применяет управляемый фазовый переворот: сначала как оракул |11⟩, затем в диффузии Grover.",he:"מפעיל היפוך פאזה מבוקר: תחילה כאורקל |11⟩ ואז בדיפוזיית Grover."}},{contains:"mz(qubits)",text:{en:"Measures both qubits in the computational Z basis.",ru:"Измеряет оба кубита в вычислительном Z-базисе.",he:"מודד את שני הקיוביטים בבסיס Z החישובי."}}]},
    {kicker:{en:"RUNTIME ADAPTER",ru:"АДАПТЕР СРЕДЫ",he:"מתאם סביבת ריצה"},title:{en:"Select a CUDA-Q target and sample",ru:"Выбор таргета CUDA-Q и измерения",he:"בחירת יעד CUDA-Q ודגימה"},summary:{en:"The portable target is qpp-cpu. A missing CUDA-Q installation produces structured status instead of a false success.",ru:"Переносимый таргет — qpp-cpu. При отсутствии CUDA-Q возвращается структурированный статус, а не ложный успех.",he:"היעד הנייד הוא qpp-cpu. היעדר CUDA-Q מחזיר סטטוס מובנה במקום הצלחה שגויה."},source:"../scientific_backend/hybrid_quantum_asic_demo.py",sourceLabel:{en:"Runtime adapter",ru:"Адаптер среды",he:"מתאם סביבה"},start:"def run_quantum_kernel",end:"def run_demo",substeps:[{title:{en:"Availability",ru:"Доступность",he:"זמינות"},start:"if cudaq is None",end:"cudaq.set_target"},{title:{en:"Execute",ru:"Исполнение",he:"הרצה"},start:"cudaq.set_target",end:"return {"}],notes:[{contains:"cudaq.set_target",text:{en:"Chooses qpp-cpu by default; an NVIDIA or cloud target can be supplied only when that backend is configured.",ru:"По умолчанию выбирает qpp-cpu; NVIDIA или облачный таргет допустим только при настроенном backend.",he:"בוחר qpp-cpu כברירת מחדל; יעד NVIDIA או ענן אפשרי רק כאשר ה-backend מוגדר."}},{contains:"cudaq.sample",text:{en:"Executes repeated circuit shots and returns a measured bitstring histogram.",ru:"Выполняет повторные shots схемы и возвращает гистограмму измеренных битовых строк.",he:"מריץ shots חוזרים של המעגל ומחזיר היסטוגרמת מחרוזות ביטים."}}]},
    {kicker:{en:"END-TO-END CONTRACT",ru:"СКВОЗНОЙ КОНТРАКТ",he:"חוזה מקצה לקצה"},title:{en:"Connect the accepted address to the kernel",ru:"Связь принятого адреса с ядром",he:"חיבור הכתובת שהתקבלה לליבה"},summary:{en:"The orchestrator records inputs, filtered rows, the explicit address mapping, quantum output, and the scientific boundary in one result object.",ru:"Оркестратор сохраняет входы, отфильтрованные строки, явное отображение адреса, квантовый результат и научную границу в одном объекте.",he:"המתזמר שומר קלטים, שורות מסוננות, מיפוי כתובת מפורש, פלט קוונטי והגבול המדעי באובייקט תוצאה אחד."},source:"../scientific_backend/hybrid_quantum_asic_demo.py",sourceLabel:{en:"End-to-end Python",ru:"Сквозной Python",he:"Python מקצה לקצה"},start:"def run_demo",end:"def main",substeps:[{title:{en:"Filter + rank",ru:"Фильтр и выбор",he:"סינון ודירוג"},start:"accepted =",end:"quantum ="},{title:{en:"Execute conditionally",ru:"Условное исполнение",he:"הרצה מותנית"},start:"quantum =",end:"return {"},{title:{en:"Provenance record",ru:"Запись происхождения",he:"רשומת מקור"},start:"return {",end:"def main"}],notes:[{contains:"address_contract_ok",text:{en:"Checks the documented one-to-one mapping before invoking the quantum stage.",ru:"Проверяет документированное взаимно-однозначное отображение до вызова квантового этапа.",he:"בודק את המיפוי החד־חד־ערכי המתועד לפני הפעלת השלב הקוונטי."}},{contains:"scientificBoundary",text:{en:"Prevents the architecture demo from being misread as a multiquark prediction.",ru:"Не позволяет принять демонстрацию архитектуры за прогноз мультикварковой системы.",he:"מונע פירוש של הדגמת הארכיטקטורה כניבוי מערכת מרובת־קווארקים."}}]}
  ],
  sources:[
    {title:{en:"Hybrid host and CUDA-Q source",ru:"Hybrid host и CUDA-Q",he:"מקור מארח היברידי ו-CUDA-Q"},text:{en:"Software reference, optional CUDA-Q kernel, runtime adapter, and provenance result.",ru:"Программный эталон, опциональное ядро CUDA-Q, адаптер среды и результат с provenance.",he:"ייחוס תוכנה, ליבת CUDA-Q אופציונלית, מתאם סביבה ותוצאת provenance."},path:"../scientific_backend/hybrid_quantum_asic_demo.py"},
    {title:{en:"Synthesizable candidate filter",ru:"Синтезируемый фильтр кандидатов",he:"מסנן מועמדים ניתן לסינתזה"},text:{en:"The narrow ASIC/FPGA partition with a ready/valid streaming interface.",ru:"Узкая ASIC/FPGA-часть с потоковым ready/valid-интерфейсом.",he:"מחיצת ASIC/FPGA צרה עם ממשק זרימה ready/valid."},path:"../hardware/hybrid_quantum_asic/hybrid_candidate_filter.sv"},
    {title:{en:"RTL testbench",ru:"RTL-testbench",he:"RTL testbench"},text:{en:"A passing candidate and a rejected non-zero-triality candidate are checked cycle by cycle.",ru:"По тактам проверяются проходящий кандидат и отклонение ненулевой триальности.",he:"מועמד עובר ומועמד triality לא־אפס שנדחה נבדקים מחזור אחר מחזור."},path:"../hardware/hybrid_quantum_asic/tb_hybrid_candidate_filter.sv"},
    {title:{en:"Automated Python contract tests",ru:"Автоматические Python-тесты",he:"בדיקות חוזה Python אוטומטיות"},text:{en:"Tests keep the selected address, margin, and scientific wording stable.",ru:"Тесты фиксируют выбранный адрес, запас и научную формулировку.",he:"בדיקות שומרות על הכתובת, המרווח והניסוח המדעי."},path:"../tests/test_hybrid_quantum_asic_demo.py"}
  ],
  boundary:{en:"This example validates an inspectable software/RTL/quantum interface. The committed RTL can be simulated and synthesized; the CUDA-Q kernel can run on qpp-cpu where CUDA-Q is installed. It does not calculate hadron energies, replace lattice QCD, demonstrate quantum advantage, or claim execution on this computer's AMD GPU. NVIDIA's CUDA-Q GPU simulator requires a supported NVIDIA GPU; Matter Frontier Lab uses separate DirectML paths for the Radeon hardware.",ru:"Пример проверяет прозрачный интерфейс между программой, RTL и квантовым ядром. Добавленный RTL можно симулировать и синтезировать; ядро CUDA-Q работает на qpp-cpu там, где установлена CUDA-Q. Оно не вычисляет энергии адронов, не заменяет lattice QCD, не доказывает квантовое преимущество и не заявляет выполнение на AMD-GPU этого компьютера. GPU-симулятор CUDA-Q от NVIDIA требует поддерживаемую NVIDIA-карту; для Radeon в Matter Frontier Lab используются отдельные пути DirectML.",he:"הדוגמה מאמתת ממשק שקוף בין תוכנה, RTL וליבה קוונטית. ניתן לדמות ולסנתז את ה-RTL שבמאגר; ליבת CUDA-Q יכולה לרוץ על qpp-cpu במקום שבו CUDA-Q מותקנת. היא אינה מחשבת אנרגיות האדרונים, אינה מחליפה lattice QCD, אינה מוכיחה יתרון קוונטי ואינה טוענת להרצה על GPU מסוג AMD במחשב זה. סימולטור ה-GPU של CUDA-Q דורש GPU נתמך של NVIDIA; עבור Radeon משתמש Matter Frontier Lab בנתיבי DirectML נפרדים."}
};
